### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'echo "hi"''

### ISSUE THREAD

**Issue by BitPigeon** [Saadmairaj/tkterminal#12]
This project is __awesome__! As far as I am aware there is only one error:
When I try to run `echo "hi"` or any other __[two word]__ command while not in shell mode, it returns

```yaml
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/therealpenguin/.local/lib/python3.9/site-packages/tkterminal/utils.py", line 43, in wrapper
    kw['return'] = kw['function'](*args, **kwargs)
  File "/home/therealpenguin/.local/lib/python3.9/site-packages/tkterminal/ternimal.py", line 157, in _run_on_return
    with Popen(cmd, stdout=PIPE, stderr=PIPE, stdin=stdin,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'echo "hi"'
```

**Comment by BitPigeon** [comment]
In my experience this means `Popen()` is used with a string: `'echo "hi"'` rather than a list: `['echo', '"hi"]`.
