### ISSUE TITLE
issue with control + c.

### ISSUE THREAD

**Issue by 3022-2** [Saadmairaj/tkterminal#21]
Traceback (most recent call last):
  File "C:\Users\lucre\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lucre\AppData\Local\Programs\Python\Python312\Lib\site-packages\tkterminal\ternimal.py", line 203, in _on_keypress
    or ((insert_idx.column <= self._limit_backspace or False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType' 

when control + c

ctrl + c doesnt stop subprocess

**Comment by willdone-mt** [comment]
I think there is a closed issue which should relate to your issue, maybe this? [TypeError: '<=' not supported between instances of 'int' and 'NoneType'](https://github.com/Saadmairaj/tkterminal/issues/15)
